[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sketchyopts"
requires-python = ">=3.9"

[project.optional-dependencies]
test = []
docs = [
  "sphinx-book-theme", 
  "sphinx-autodoc-typehints",
]

[tool.pyright]
include = ["sketchyopts"]
